import type { Language } from '@/lib/site';
type Copy = { category: string; headline: string; summary: string; context: string; system: string; complexity: string; engineering: string; impact: string; decisions: [string, string][] };
export type Project = { slug: string; number: string; name: string; short: string; repo?: string; stack: string[]; flow: Record<Language,string[]>; es: Copy; en: Copy };
export const projects: Project[] = [
  {
    slug: 'servifood-orders', number: '01', name: 'App de Pedidos · ServiFood', short: 'App de Pedidos', repo: 'App_de_pedidos',
    stack: ['React 19', 'Vite 7', 'Supabase', 'PostgreSQL', 'RLS', 'RPC', 'Edge Functions', 'Vitest', 'ExcelJS', 'jsPDF', 'Render'],
    flow: { es: ['Interfaz', 'Usuarios y acceso', 'Base de datos', 'Automatizaciones', 'Excel / PDF'], en: ['Interface', 'Users and access', 'Database', 'Automation', 'Excel / PDF'] },
    es: {
      category: 'PEDIDOS · ADMINISTRACIÓN · REPORTES', headline: 'El pedido era\nsolo el principio.',
      summary: 'Una app para que distintas empresas hagan sus pedidos y ServiFood gestione menús, usuarios, horarios, etiquetas, remitos y reportes desde el mismo lugar.',
      context: 'La necesidad inicial era ordenar los pedidos diarios. Con el uso aparecieron más necesidades: empresas con reglas distintas, horarios, sedes, reportes, etiquetas, remitos y tareas administrativas.',
      system: 'Construí una plataforma que conecta el pedido de cada usuario con la operación diaria de ServiFood. Desde el mismo sistema se administran pedidos, menús, usuarios, consumo, cafetería, etiquetas, remitos y reportes.',
      complexity: 'Cada empresa puede tener reglas y horarios distintos, y no todos los usuarios deben ver o hacer lo mismo. Además, hay procesos automáticos que deben ejecutarse sin duplicar información.',
      engineering: 'React y Vite resuelven la interfaz. Supabase Auth identifica usuarios; PostgreSQL, RLS y RPC aplican permisos y reglas. Edge Functions y tareas programadas automatizan procesos. ExcelJS y jsPDF generan documentos de trabajo.',
      impact: 'Centraliza tareas que antes estaban separadas y permite que usuarios y administración trabajen sobre la misma información durante toda la jornada.',
      decisions: [['Los permisos no dependen solo de la pantalla', 'Las acciones sensibles también se validan junto a los datos para evitar accesos incorrectos.'], ['Los reportes forman parte del flujo', 'Excel, PDF, remitos y paneles permiten que la información siga siendo útil fuera de la pantalla.'], ['La aplicación sigue creciendo después del deploy', 'Los cambios nacen del uso real: errores, nuevas empresas, nuevas reglas y necesidades operativas.']],
    },
    en: {
      category: 'ORDERS · ADMINISTRATION · REPORTS', headline: 'The order was\njust the beginning.',
      summary: 'An app where different companies place daily food orders while ServiFood manages menus, users, schedules, labels, delivery notes and reports in one place.',
      context: 'The first need was simple: organize daily orders. Real use quickly added company-specific rules, schedules, locations, reports, labels, delivery notes and admin tasks.',
      system: 'I built a platform that connects each user order with ServiFood’s daily operation. Orders, menus, users, consumption, cafeteria workflows, labels, delivery notes and reports live in the same system.',
      complexity: 'Each company can have different rules and schedules, and users need different levels of access. Automated processes also need to run safely without duplicating data.',
      engineering: 'React and Vite power the interface. Supabase Auth identifies users; PostgreSQL, RLS and RPC handle permissions and rules. Edge Functions and scheduled jobs automate processes. ExcelJS and jsPDF generate working documents.',
      impact: 'It brings separate tasks into one place so users and administrators work with the same information throughout the day.',
      decisions: [['Permissions go beyond the screen', 'Sensitive actions are also checked close to the data instead of relying only on the interface.'], ['Reports are part of the workflow', 'Excel, PDF, delivery notes and dashboards keep the information useful outside the app.'], ['The app keeps evolving after launch', 'Changes come from real use: bugs, new companies, new rules and operational needs.']],
    },
  },
  {
    slug: 'midnight-pass', number: '02', name: 'MIDNIGHT PASS', short: 'MIDNIGHT PASS', repo: 'Midnight_pass',
    stack: ['React', 'Three.js', 'React Three Fiber', 'React Three Rapier', 'Rapier', 'Zustand', 'Vite'],
    flow: { es: ['Controles', 'Física a 60 Hz', 'Movimiento del vehículo', 'Mundo 3D', 'Telemetría'], en: ['Controls', '60 Hz physics', 'Vehicle movement', '3D world', 'Telemetry'] },
    es: {
      category: 'JUEGO DE CONDUCCIÓN · PROYECTO PERSONAL', headline: 'Otro tipo\nde sistema.',
      summary: 'Mi juego de conducción para navegador: rutas conectadas, física en tiempo real, tres cámaras y un mundo 3D que sigo expandiendo.',
      context: 'Quería llevar lo que había aprendido en aplicaciones web a un problema completamente distinto: hacer que un vehículo, una carretera y un mundo 3D se sientan coherentes mientras todo corre en el navegador.',
      system: 'MIDNIGHT PASS conecta Saltwind Village, Cliff Road, Pine Pass, Old Harbor y Outskirts. El vehículo KASAI 82 / 1600 GT se puede conducir con teclado o controles táctiles y dispone de tres cámaras.',
      complexity: 'El terreno visible y las colisiones tienen que coincidir, el vehículo debe reaccionar de forma estable y el mundo debe mantenerse fluido sin cargar elementos innecesarios.',
      engineering: 'Rapier controla un chasis dinámico a 60 Hz con cuatro raycasts. El mundo se divide en sectores, usa LOD, materiales compartidos y vegetación instanciada. La telemetría está separada del estado de los menús.',
      impact: 'Es mi laboratorio personal para aprender física, gráficos 3D, rendimiento y diseño de mundos interactivos aplicando criterios de ingeniería web.',
      decisions: [['La física manda sobre el movimiento', 'El vehículo visual sigue el estado físico en lugar de intentar simular movimiento por separado.'], ['El mundo se divide en sectores', 'LOD, colisiones cercanas e instancing ayudan a mantener el rendimiento.'], ['La UI no se mezcla con la telemetría', 'Los datos que cambian cada frame siguen un camino distinto al de menús y controles.']],
    },
    en: {
      category: 'DRIVING GAME · PERSONAL PROJECT', headline: 'A different\nkind of system.',
      summary: 'My browser driving game: connected roads, real-time physics, three cameras and a 3D world I keep expanding.',
      context: 'I wanted to take what I had learned from web applications into a very different problem: making a vehicle, a road and a 3D world feel consistent while everything runs in the browser.',
      system: 'MIDNIGHT PASS connects Saltwind Village, Cliff Road, Pine Pass, Old Harbor and Outskirts. The KASAI 82 / 1600 GT can be driven with keyboard or touch controls and has three cameras.',
      complexity: 'Visible terrain and collisions need to match, the car needs stable behavior, and the world must stay smooth without loading unnecessary work.',
      engineering: 'Rapier drives a dynamic chassis at 60 Hz with four raycasts. The world is split into sectors and uses LOD, shared materials and instanced vegetation. Telemetry is kept separate from menu state.',
      impact: 'It is my personal lab for learning physics, 3D graphics, performance and interactive world design with a web engineering mindset.',
      decisions: [['Physics controls movement', 'The visual car follows the physical state instead of simulating a second movement system.'], ['The world is split into sectors', 'LOD, nearby collisions and instancing help keep performance under control.'], ['UI and telemetry stay separate', 'Per-frame data follows a different path from menus and controls.']],
    },
  },
  {
    slug: 'servifood-tracking', number: '03', name: 'ServiFood Tracking · Panel de Mantenimiento', short: 'ServiFood Tracking', repo: 'app_tracking_laboral_sf',
    stack: ['React', 'Vite', 'Supabase', 'PostgreSQL', 'SQL', 'Excel'],
    flow: { es: ['Trabajos', 'Personas y permisos', 'Datos', 'Vehículos y activos', 'Reportes'], en: ['Jobs', 'People and permissions', 'Data', 'Vehicles and assets', 'Reports'] },
    es: {
      category: 'MANTENIMIENTO · VEHÍCULOS · TRABAJOS', headline: 'El trabajo de campo,\nordenado en una app.',
      summary: 'Una plataforma para registrar trabajos, organizar personal, seguir vehículos, combustible, mantenimiento, costos, activos y vencimientos.',
      context: 'Los trabajos de mantenimiento ocurren en planta, en vehículos y con distintas personas. Hacía falta reunir esa información sin perder el contexto de cada tarea.',
      system: 'La app reúne trabajos diarios, solicitudes, trabajadores, grupos, costos y reportes. También incorpora vehículos, choferes, combustible, kilometraje, recorridos, mantenimiento y activos de planta.',
      complexity: 'Hay que relacionar personas, equipos, recorridos y mantenimientos sin volver la interfaz difícil de usar para quienes cargan información todos los días.',
      engineering: 'Está desarrollada con React y Vite sobre Supabase y PostgreSQL. Incluye roles, permisos, paneles, exportación a Excel y ayudas dentro de la propia aplicación.',
      impact: 'Permite registrar tareas, seguir solicitudes y consultar el historial de vehículos y activos desde un mismo lugar.',
      decisions: [['Representar el trabajo real', 'Trabajos, activos y vehículos conservan relaciones y contexto en lugar de quedar como registros aislados.'], ['Guardar el historial', 'Recorridos, mantenimientos y vencimientos son útiles porque se pueden seguir en el tiempo.'], ['Pensar en el uso diario', 'Paneles, filtros, reportes y ayuda integrada reducen fricción en tareas repetidas.']],
    },
    en: {
      category: 'MAINTENANCE · VEHICLES · JOBS', headline: 'Field work,\norganized in one app.',
      summary: 'A platform for jobs, staff, vehicles, fuel, maintenance, costs, assets and document deadlines.',
      context: 'Maintenance happens across facilities, vehicles and different teams. The information needed one shared place without losing the context of each job.',
      system: 'The app brings together daily jobs, requests, workers, groups, costs and reports, plus vehicles, drivers, fuel, mileage, routes, maintenance and plant assets.',
      complexity: 'People, equipment, journeys and maintenance events need to stay connected without making everyday data entry difficult.',
      engineering: 'It is built with React and Vite on Supabase and PostgreSQL, with roles, permissions, dashboards, Excel exports and in-app guidance.',
      impact: 'It lets teams record work, follow requests and review vehicle and asset history in one place.',
      decisions: [['Represent real work', 'Jobs, assets and vehicles keep their relationships and context instead of becoming isolated records.'], ['Keep the history', 'Routes, maintenance and deadlines become more useful when they can be followed over time.'], ['Design for daily use', 'Dashboards, filters, reports and built-in guidance reduce friction in repeated tasks.']],
    },
  },
  {
    slug: 'servifood-analytics', number: '04', name: 'Servifood Analysis App', short: 'Analysis App', repo: 'analisis_app_servifood',
    stack: ['React 18', 'Vite', 'Material UI', 'Node.js 20', 'Express', 'Supabase', 'PostgreSQL', 'ExcelJS'],
    flow: { es: ['Excel', 'Validación', 'Base de datos', 'Paneles', 'Análisis'], en: ['Excel', 'Validation', 'Database', 'Dashboards', 'Analysis'] },
    es: {
      category: 'ANÁLISIS · EXCEL · CALIDAD', headline: 'De muchos archivos\na información útil.',
      summary: 'Una aplicación interna que procesa Excel, guarda historial y reúne análisis, documentación, certificaciones y administración de usuarios.',
      context: 'Los archivos de trabajo tenían información útil, pero estaba repartida y era difícil mantener un historial consistente para comparar resultados.',
      system: 'La aplicación permite cargar y analizar Excel, revisar historial, trabajar con documentos SGC, certificaciones, declaraciones y análisis anuales, además de administrar usuarios.',
      complexity: 'Los archivos deben validarse antes de usar sus datos y cada tipo de usuario necesita acceso distinto. El procesamiento también debe estar separado de la interfaz.',
      engineering: 'El frontend usa React, Vite y Material UI. El backend usa Node.js y Express. Supabase gestiona autenticación y PostgreSQL guarda la información; ExcelJS se ocupa de leer los archivos.',
      impact: 'Convierte archivos dispersos en información que se puede consultar, comparar y volver a utilizar desde una plataforma común.',
      decisions: [['Validar antes de guardar', 'Los archivos se revisan antes de convertir su contenido en información de trabajo.'], ['Separar interfaz y procesamiento', 'Express concentra el trabajo de servidor y React se enfoca en la experiencia y la visualización.'], ['Conservar el historial', 'Cada análisis puede consultarse después y formar parte de comparaciones posteriores.']],
    },
    en: {
      category: 'ANALYSIS · EXCEL · QUALITY', headline: 'From many files\nto useful information.',
      summary: 'An internal app that processes Excel files, keeps history and brings analysis, documents, certifications and user administration together.',
      context: 'Working files contained useful information, but it was scattered and difficult to keep as a consistent history for comparison.',
      system: 'The app handles Excel uploads and analysis, history, quality documents, certifications, declarations, annual analysis and user administration.',
      complexity: 'Files need validation before their data is used, and different users need different access. Processing also needs to stay separate from the interface.',
      engineering: 'The frontend uses React, Vite and Material UI. The backend uses Node.js and Express. Supabase handles authentication, PostgreSQL stores the data and ExcelJS reads the files.',
      impact: 'It turns scattered files into information that can be reviewed, compared and reused from one shared platform.',
      decisions: [['Validate before storing', 'Files are checked before their contents become working data.'], ['Separate interface and processing', 'Express handles server work while React focuses on interaction and visualization.'], ['Keep the history', 'Each analysis remains available for later review and comparison.']],
    },
  },
  {
    slug: 'ep-consultora-sgi', number: '05', name: 'EP Consultora', short: 'EP Consultora', repo: 'Aplicacion_de_SGI',
    stack: ['React 18', 'Vite', 'React Router', 'Supabase', 'PostgreSQL', 'RLS', 'Storage', 'Edge Functions', 'Vitest', 'GitHub Actions'],
    flow: { es: ['Empresa', 'Usuarios y permisos', 'Documentos privados', 'Revisión y aprobación', 'Historial'], en: ['Company', 'Users and permissions', 'Private documents', 'Review and approval', 'History'] },
    es: {
      category: 'DOCUMENTOS · EMPRESAS · APROBACIONES', headline: 'Cada documento,\ncon su recorrido.',
      summary: 'Una plataforma multiempresa para organizar documentos, responsables, versiones, revisiones, aprobaciones, vencimientos y requisitos ISO.',
      context: 'Guardar archivos no alcanza cuando hay responsables, versiones, revisiones y aprobaciones. Además, cada empresa debe trabajar solo con su propia documentación.',
      system: 'EP Consultora centraliza documentación, usuarios, alertas y requisitos de ISO 9001, ISO 14001 e ISO 45001. Cada documento puede pasar por revisión, observaciones y aprobación, dejando historial.',
      complexity: 'Las empresas deben estar separadas entre sí y los documentos necesitan permisos, versiones y estados claros durante todo su recorrido.',
      engineering: 'React y Supabase forman la base. Auth y RLS controlan accesos; los archivos viven en Storage privado y se abren mediante enlaces firmados. El flujo de revisión y aprobación queda registrado.',
      impact: 'Permite a cada empresa organizar su documentación y seguir qué pasó con cada archivo, quién intervino y en qué estado se encuentra.',
      decisions: [['Cada empresa tiene su propio espacio', 'Los permisos evitan que una organización pueda consultar documentos de otra.'], ['Un documento tiene historia', 'Versiones, comentarios, revisores y aprobadores forman parte del mismo recorrido.'], ['Los archivos son privados', 'El acceso se entrega solo cuando corresponde y no mediante enlaces públicos permanentes.']],
    },
    en: {
      category: 'DOCUMENTS · COMPANIES · APPROVALS', headline: 'Every document\nhas a clear path.',
      summary: 'A multi-company platform for documents, owners, versions, reviews, approvals, deadlines and ISO requirements.',
      context: 'File storage is not enough when documents need owners, versions, reviews and approvals. Each company also needs to work only with its own information.',
      system: 'EP Consultora brings together documents, users, alerts and ISO 9001, ISO 14001 and ISO 45001 requirements. Documents can move through review, comments and approval while keeping history.',
      complexity: 'Companies need to stay isolated from each other while documents keep clear permissions, versions and states throughout their lifecycle.',
      engineering: 'React and Supabase form the base. Auth and RLS control access; files live in private Storage and open through signed links. Review and approval steps are recorded.',
      impact: 'Each company can organize its documentation and see what happened to every file, who took part and what state it is in.',
      decisions: [['Each company has its own space', 'Permissions prevent one organization from viewing another company’s documents.'], ['A document keeps its history', 'Versions, comments, reviewers and approvers belong to the same record.'], ['Files stay private', 'Access is granted when needed instead of exposing permanent public links.']],
    },
  },
];
export const projectCopy = (project: Project, lang: Language) => project[lang];
