import type { Language } from '@/lib/site';
type Copy = { category: string; headline: string; summary: string; context: string; system: string; complexity: string; engineering: string; impact: string; decisions: [string, string][] };
export type Project = { slug: string; number: string; name: string; short: string; repo?: string; stack: string[]; flow: string[]; es: Copy; en: Copy };
export const projects: Project[] = [
  {
    slug: 'servifood-orders', number: '01', name: 'ServiFood Order System', short: 'Orders', repo: 'App_de_pedidos',
    stack: ['React 19', 'Vite 7', 'Supabase', 'PostgreSQL', 'RLS', 'RPC', 'Edge Functions', 'Vitest', 'ExcelJS', 'jsPDF', 'Render'],
    flow: ['React / Vite', 'Supabase Auth', 'PostgreSQL / RLS', 'RPC / Edge Functions', 'Excel / PDF'],
    es: {
      category: 'PLATAFORMA OPERATIVA · MULTIEMPRESA', headline: 'El pedido era\nsolo el principio.',
      summary: 'Una necesidad diaria que evolucionó hacia un sistema de alimentación corporativa: empresas, sedes, permisos, reportes y automatizaciones.',
      context: 'La operación de alimentación reúne pedidos diarios, menús cambiantes, sedes y reglas distintas por empresa. Resolver la carga de pedidos era solo una parte: la información también tenía que servir a administración y operación.',
      system: 'Una plataforma full-stack que conecta el pedido con paneles diarios y mensuales, cafetería, etiquetas, remitos, auditoría y exportaciones. Un mismo modelo operativo atraviesa múltiples dominios de negocio.',
      complexity: 'Las reglas por empresa, los horarios de operación y los distintos niveles de administración deben convivir sin abrir accesos indebidos. Las tareas automáticas tienen que soportar reintentos sin duplicar operaciones.',
      engineering: 'React y Vite organizan la interfaz. Supabase Auth identifica al usuario; PostgreSQL, RLS y RPCs aplican permisos y lógica de datos. Edge Functions y tareas programadas cubren procesos automáticos. ExcelJS y jsPDF transforman los datos en documentos de trabajo.',
      impact: 'Permite gestionar pedidos, consultar consumo y preparar información para la operación desde una plataforma que sigue evolucionando con el uso real.',
      decisions: [['La autorización vive junto a los datos', 'Los permisos no dependen únicamente de lo que muestra la interfaz. RLS y lógica server-side sostienen el acceso por rol y empresa.'], ['Los reportes son parte del producto', 'Paneles, exportaciones y remitos permiten que la información continúe su recorrido fuera de la pantalla.'], ['El trabajo sigue después del deploy', 'Monitoreo, diagnóstico de incidentes y mantenimiento acompañan la evolución funcional.']],
    },
    en: {
      category: 'OPERATIONAL PLATFORM · MULTI-COMPANY', headline: 'The order was\njust the beginning.',
      summary: 'A daily need that grew into a corporate food operations system: companies, locations, permissions, reporting and automation.',
      context: 'Food operations involve daily orders, changing menus, multiple locations and company-specific rules. Order entry was only one part: the same information had to support administration and daily operations.',
      system: 'A full-stack platform connecting orders with daily and monthly dashboards, cafeteria workflows, labels, delivery documents, auditing and exports. One operational model spans several business domains.',
      complexity: 'Company rules, operating hours and different administrative scopes must coexist without granting unintended access. Automated jobs need to tolerate retries without duplicating operations.',
      engineering: 'React and Vite structure the interface. Supabase Auth identifies users; PostgreSQL, RLS and RPCs enforce access and data logic. Edge Functions and scheduled jobs handle automation. ExcelJS and jsPDF turn data into working documents.',
      impact: 'Enables order management, consumption reporting and preparation of operational information within a platform that continues to evolve through real use.',
      decisions: [['Authorization belongs with the data', 'Access does not depend solely on what the interface displays. RLS and server-side logic support role and company boundaries.'], ['Reporting is part of the product', 'Dashboards, exports and delivery documents let information continue its journey beyond the screen.'], ['The work continues after deployment', 'Monitoring, incident diagnosis and maintenance accompany functional development.']],
    },
  },
  {
    slug: 'midnight-pass', number: '02', name: 'MIDNIGHT PASS', short: 'Realtime 3D', repo: 'Midnight_pass',
    stack: ['React', 'Three.js', 'React Three Fiber', 'React Three Rapier', 'Rapier', 'Zustand', 'Vite'],
    flow: ['Input', 'Rapier / 60 Hz', 'Vehicle dynamics', 'Three.js / R3F', 'Telemetry'],
    es: {
      category: 'INGENIERÍA INTERACTIVA · PROYECTO PROPIO', headline: 'Otro tipo\nde sistema.',
      summary: 'Simulación vehicular en tiempo real. Un mundo conectado, física dinámica y entornos procedurales construidos para la web.',
      context: 'Explorar qué ocurre cuando React deja de organizar formularios y empieza a coordinar un mundo interactivo: conducción, física, cámaras y paisaje en tiempo real.',
      system: 'Un mundo de conducción que conecta Saltwind Village, Cliff Road, Pine Pass, Old Harbor y Outskirts. Un vehículo ficticio, KASAI 82 / 1600 GT, recorre carreteras y calles con controles de teclado y táctiles.',
      complexity: 'Mantener coherencia entre terreno visible y colisiones, separar el movimiento físico de la representación visual y recuperar el vehículo sobre una carretera segura sin mezclar telemetría con estado de interfaz.',
      engineering: 'Un chasis dinámico Rapier recibe impulsos a 60 Hz y utiliza cuatro raycasts. El mundo se divide en sectores, con LOD, materiales compartidos y vegetación determinística instanciada. Tres cámaras ofrecen distintas lecturas del vehículo.',
      impact: 'Un laboratorio propio para profundizar en simulación, geometría procedural, presupuestos de renderizado y arquitectura de estado en tiempo real.',
      decisions: [['Una autoridad de movimiento', 'La dinámica física controla el chasis; la representación visual sigue ese estado.'], ['Un mundo organizado por sectores', 'Terreno con LOD, colisiones cercanas e instancing reducen trabajo repetido.'], ['Telemetría separada de la UI', 'Los datos por frame tienen un recorrido distinto al estado de menús y controles.']],
    },
    en: {
      category: 'INTERACTIVE ENGINEERING · PERSONAL PROJECT', headline: 'A different\nkind of system.',
      summary: 'Real-time vehicle simulation. A connected world, dynamic physics and procedural environments built for the web.',
      context: 'Exploring what happens when React moves beyond forms to coordinate an interactive world: driving, physics, cameras and scenery in real time.',
      system: 'A driving world connecting Saltwind Village, Cliff Road, Pine Pass, Old Harbor and Outskirts. A fictional KASAI 82 / 1600 GT travels roads and residential streets with keyboard and touch controls.',
      complexity: 'Keeping visible terrain and collision geometry consistent, separating physical movement from visual representation, and recovering the vehicle onto a safe road without coupling telemetry to UI state.',
      engineering: 'A dynamic Rapier chassis receives impulses at 60 Hz and uses four raycasts. The world is divided into sectors with LOD, shared materials and deterministic instanced vegetation. Three cameras offer different views of the vehicle.',
      impact: 'A personal laboratory for simulation, procedural geometry, rendering budgets and real-time state architecture.',
      decisions: [['One authority for movement', 'Physical dynamics control the chassis; the visual representation follows that state.'], ['A world organized into sectors', 'Terrain LOD, nearby collisions and instancing reduce repeated work.'], ['Telemetry separate from UI', 'Per-frame data follows a different path from menu and control state.']],
    },
  },
  {
    slug: 'servifood-tracking', number: '03', name: 'ServiFood Tracking', short: 'Tracking', repo: 'app_tracking_laboral_sf',
    stack: ['React', 'Vite', 'Supabase', 'PostgreSQL', 'SQL', 'Excel'], flow: ['React / Vite', 'Auth / Roles', 'PostgreSQL', 'Operations', 'Reports'],
    es: {
      category: 'OPERACIÓN · MANTENIMIENTO', headline: 'Software que entiende\nel trabajo de campo.',
      summary: 'Trabajos, cuadrillas, vehículos y activos. Procesos físicos conectados mediante información que se puede seguir.',
      context: 'Las tareas de mantenimiento no suceden dentro de una aplicación. Ocurren en planta, en vehículos y en el trabajo de las cuadrillas. El sistema necesita representar esa realidad con claridad.',
      system: 'Una plataforma para trabajos diarios, solicitudes, trabajadores, costos y reportes, con dominios de vehículos, combustible, kilometraje, mantenimiento, activos y vencimientos.',
      complexity: 'Relacionar personas, equipos, recorridos y eventos de mantenimiento, manteniendo permisos y ofreciendo una interfaz usable para tareas operativas diversas.',
      engineering: 'React y Vite sobre Supabase y PostgreSQL. Modelado por dominios operativos, roles y permisos, dashboards, exportación a Excel y un tutorial integrado para acompañar el uso.',
      impact: 'Permite registrar trabajo, seguir solicitudes y consultar el historial operativo de vehículos y activos en un mismo entorno.',
      decisions: [['Modelar el proceso físico', 'Trabajos, activos y vehículos conservan su contexto y sus relaciones.'], ['La historia también es un dato', 'Mantenimiento preventivo y correctivo, recorridos y vencimientos necesitan seguimiento.'], ['Diseñar para el uso cotidiano', 'Dashboards, reportes y ayuda integrada acompañan las tareas del usuario.']],
    },
    en: {
      category: 'OPERATIONS · MAINTENANCE', headline: 'Software that understands\nwork in the field.',
      summary: 'Jobs, crews, vehicles and assets. Physical processes connected through information that can be tracked.',
      context: 'Maintenance does not happen inside an application. It happens on site, in vehicles and through the work of crews. The system needs to represent that reality clearly.',
      system: 'A platform for daily jobs, requests, workers, costs and reports, covering vehicles, fuel, mileage, maintenance, assets and expiration dates.',
      complexity: 'Connecting people, equipment, journeys and maintenance events while maintaining permissions and a usable interface for varied operational tasks.',
      engineering: 'React and Vite over Supabase and PostgreSQL. Operational domain modeling, roles and permissions, dashboards, Excel exports and an integrated tutorial support everyday use.',
      impact: 'Enables work recording, request tracking and access to vehicle and asset history within one environment.',
      decisions: [['Model the physical process', 'Jobs, assets and vehicles retain their context and relationships.'], ['History is data too', 'Preventive and corrective maintenance, journeys and expiration dates need tracking.'], ['Design for daily use', 'Dashboards, reports and integrated help support the user’s tasks.']],
    },
  },
  {
    slug: 'servifood-analytics', number: '04', name: 'ServiFood Analytics', short: 'Analytics', repo: 'analisis_app_servifood',
    stack: ['React 18', 'Vite', 'Material UI', 'Node.js 20', 'Express', 'Supabase', 'PostgreSQL', 'ExcelJS'], flow: ['Excel', 'Express / Validation', 'PostgreSQL', 'React / Material UI', 'Analysis'],
    es: {
      category: 'DATOS · BACKEND SEPARADO', headline: 'De archivos dispersos\na información útil.',
      summary: 'Ingesta de Excel, validación server-side y análisis. Una plataforma interna para trabajar con información operativa y de calidad.',
      context: 'Los archivos de trabajo contienen información valiosa, pero requieren procesamiento, validación e historial para convertirse en una base de análisis consistente.',
      system: 'Una aplicación interna para carga y análisis de Excel, historial, documentos SGC, certificaciones, declaraciones, análisis anual y administración de usuarios.',
      complexity: 'Validar archivos y registros antes de utilizarlos, separar responsabilidades entre cliente y servidor y gestionar acceso según roles de administración, nutrición y usuario.',
      engineering: 'Frontend React 18, Vite y Material UI; backend Node.js 20 y Express. Supabase Auth valida sesiones y PostgreSQL conserva los datos. El servidor procesa Excel y aplica validaciones antes de generar resultados.',
      impact: 'Permite consultar análisis e historial, visualizar desviaciones y gestionar documentación en una plataforma interna común.',
      decisions: [['El servidor valida', 'La carga de un archivo es una frontera de entrada de datos, no solo un control de interfaz.'], ['Responsabilidades separadas', 'Express concentra procesamiento y APIs; React se ocupa de interacción y visualización.'], ['Información con continuidad', 'El historial conecta cada análisis con el trabajo posterior.']],
    },
    en: {
      category: 'DATA · SEPARATE BACKEND', headline: 'From scattered files\nto useful information.',
      summary: 'Excel ingestion, server-side validation and analysis. An internal platform for operational and quality information.',
      context: 'Working files hold valuable information, but need processing, validation and history to become a consistent basis for analysis.',
      system: 'An internal application for Excel uploads and analysis, history, quality management documents, certifications, declarations, annual analysis and user administration.',
      complexity: 'Validating files and records before use, separating client and server responsibilities, and managing access for administration, nutrition and user roles.',
      engineering: 'React 18, Vite and Material UI frontend; Node.js 20 and Express backend. Supabase Auth validates sessions and PostgreSQL stores data. The server processes Excel and applies validation before producing results.',
      impact: 'Enables analysis and history review, deviation visualization and document management within a shared internal platform.',
      decisions: [['The server validates', 'A file upload is a data boundary, not just an interface control.'], ['Separate responsibilities', 'Express handles processing and APIs; React handles interaction and visualization.'], ['Information with continuity', 'History connects each analysis to the work that follows.']],
    },
  },
  {
    slug: 'ep-consultora-sgi', number: '05', name: 'EP Consultora / SGI', short: 'SGI', repo: 'Aplicacion_de_SGI',
    stack: ['React 18', 'Vite', 'React Router', 'Supabase', 'PostgreSQL', 'RLS', 'Storage', 'Edge Functions', 'Vitest', 'GitHub Actions'], flow: ['Organizations', 'Auth / RLS', 'Private storage', 'Review / Approval', 'Traceability'],
    es: {
      category: 'MULTI-TENANT · GESTIÓN DOCUMENTAL', headline: 'Cada documento,\ncon su recorrido.',
      summary: 'Organizaciones separadas, revisiones y aprobaciones. Gestión documental y trazabilidad para sistemas integrados de gestión.',
      context: 'La gestión documental necesita algo más que almacenar archivos: responsables, versiones, revisiones, aprobación y evidencia de lo que cambió. En un entorno multiempresa, cada organización también necesita límites de acceso.',
      system: 'Una plataforma de gestión documental, cumplimiento y trazabilidad con onboarding, roles globales y por empresa, vencimientos, alertas y requisitos estructurados de ISO 9001, ISO 14001 e ISO 45001.',
      complexity: 'Mantener aislamiento entre organizaciones mientras cada documento recorre responsables, revisores y aprobadores, con versiones y comentarios.',
      engineering: 'React, React Router y Supabase. Auth y RLS sostienen los permisos; Storage privado y URLs firmadas controlan el acceso a archivos. Los workflows organizan revisión, aprobación y trazabilidad.',
      impact: 'Permite gestionar el ciclo de un documento y consultar su recorrido dentro de una organización. La plataforma apoya procesos de gestión; no implica una certificación ISO del software.',
      decisions: [['La organización define el límite', 'Los permisos deben preservar el aislamiento de datos entre empresas.'], ['Un archivo tiene un ciclo de vida', 'Versiones, revisores y aprobadores forman parte del modelo documental.'], ['Acceso privado a documentos', 'Storage privado y URLs firmadas acompañan las reglas de autorización.']],
    },
    en: {
      category: 'MULTI-TENANT · DOCUMENT MANAGEMENT', headline: 'Every document\nhas a journey.',
      summary: 'Separate organizations, reviews and approvals. Document management and traceability for integrated management systems.',
      context: 'Document management requires more than file storage: owners, versions, reviews, approval and evidence of changes. In a multi-company environment, each organization also needs access boundaries.',
      system: 'A document management, compliance and traceability platform with onboarding, global and company roles, expiration dates, alerts and structured requirements for ISO 9001, ISO 14001 and ISO 45001.',
      complexity: 'Maintaining organizational isolation as each document moves through owners, reviewers and approvers, with versions and comments.',
      engineering: 'React, React Router and Supabase. Auth and RLS support permissions; private Storage and signed URLs control file access. Workflows organize review, approval and traceability.',
      impact: 'Enables document lifecycle management and review of its history within an organization. The platform supports management processes; this does not imply ISO certification of the software.',
      decisions: [['The organization defines the boundary', 'Permissions must preserve data isolation between companies.'], ['A file has a lifecycle', 'Versions, reviewers and approvers are part of the document model.'], ['Private document access', 'Private Storage and signed URLs work alongside authorization rules.']],
    },
  },
];
export const projectCopy = (project: Project, lang: Language) => project[lang];
