import type { Language } from '@/lib/site';
type Copy = { category: string; headline: string; summary: string; context: string; system: string; complexity: string; engineering: string; impact: string; decisions: [string, string][] };
export type Project = { slug: string; number: string; name: string; short: string; repo?: string; stack: string[]; flow: Record<Language,string[]>; es: Copy; en: Copy };
export const projects: Project[] = [
  {
    slug: 'servifood-orders', number: '01', name: 'App de Pedidos · ServiFood', short: 'App de Pedidos', repo: 'App_de_pedidos',
    stack: ['React 19', 'Vite 7', 'Supabase', 'PostgreSQL', 'RLS', 'RPC', 'Edge Functions', 'Vitest', 'ExcelJS', 'jsPDF', 'Render'],
    flow: { es: ['Interfaz', 'Usuarios y acceso', 'Base de datos', 'Automatizaciones', 'Excel / PDF'], en: ['Interface', 'Users and access', 'Database', 'Automation', 'Excel / PDF'] },
    es: {
      category: 'PEDIDOS · ADMINISTRACIÓN · REPORTES', headline: 'El pedido era\nsolo el principio.',
      summary: 'Una app para que distintas empresas hagan sus pedidos y ServiFood gestione menús, usuarios, horarios, etiquetas, remitos y reportes desde el mismo lugar.',
      context: 'La necesidad inicial era ordenar los pedidos diarios. Con el uso aparecieron más necesidades: empresas con reglas distintas, horarios, sedes, reportes, etiquetas, remitos y tareas administrativas.',
      system: 'Construí una plataforma que conecta el pedido de cada usuario con la operación diaria de ServiFood. Desde el mismo sistema se administran pedidos, menús, usuarios, consumo, cafetería, etiquetas, remitos y reportes.',
      complexity: 'Cada empresa puede tener reglas y horarios distintos, y no todos los usuarios deben ver o hacer lo mismo. Además, hay procesos automáticos que deben ejecutarse sin duplicar información.',
      engineering: 'React y Vite resuelven la interfaz. Supabase Auth identifica usuarios; PostgreSQL, RLS y RPC aplican permisos y reglas. Edge Functions y tareas programadas automatizan procesos. ExcelJS y jsPDF generan documentos de trabajo.',
      impact: 'Centraliza tareas que antes estaban separadas y permite que usuarios y administración trabajen sobre la misma información durante toda la jornada.',
      decisions: [['Los permisos no dependen solo de la pantalla', 'Las acciones sensibles también se validan junto a los datos para evitar accesos incorrectos.'], ['Los reportes forman parte del flujo', 'Excel, PDF, remitos y paneles permiten que la información siga siendo útil fuera de la pantalla.'], ['La aplicación sigue creciendo después del deploy', 'Los cambios nacen del uso real: errores, nuevas empresas, nuevas reglas y necesidades operativas.']],
    },
    en: {
      category: 'ORDERS · ADMINISTRATION · REPORTS', headline: 'The order was\njust the beginning.',
      summary: 'An app where different companies place daily food orders while ServiFood manages menus, users, schedules, labels, delivery notes and reports in one place.',
      context: 'The first need was simple: organize daily orders. Real use quickly added company-specific rules, schedules, locations, reports, labels, delivery notes and admin tasks.',
      system: 'I built a platform that connects each user order with ServiFood’s daily operation. Orders, menus, users, consumption, cafeteria workflows, labels, delivery notes and reports live in the same system.',
      complexity: 'Each company can have different rules and schedules, and users need different levels of access. Automated processes also need to run safely without duplicating data.',
      engineering: 'React and Vite power the interface. Supabase Auth identifies users; PostgreSQL, RLS and RPC handle permissions and rules. Edge Functions and scheduled jobs automate processes. ExcelJS and jsPDF generate working documents.',
      impact: 'It brings separate tasks into one place so users and administrators work with the same information throughout the day.',
      decisions: [['Permissions go beyond the screen', 'Sensitive actions are also checked close to the data instead of relying only on the interface.'], ['Reports are part of the workflow', 'Excel, PDF, delivery notes and dashboards keep the information useful outside the app.'], ['The app keeps evolving after launch', 'Changes come from real use: bugs, new companies, new rules and operational needs.']],
    },
  },
  {
    slug: 'rpg-premium', number: '02', name: 'RPG Premium', short: 'RPG Premium', repo: 'roguelike_premium',
    stack: ['Godot 4.7', 'GDScript', 'PC', 'Android', 'Procedural generation', 'Automated tests', 'Performance'],
    flow: { es: ['Elegir héroe', 'Capítulos y modos', 'Combate y salas', 'Recompensas y perks', 'Progresión'], en: ['Choose a hero', 'Chapters and modes', 'Combat and rooms', 'Rewards and perks', 'Progression'] },
    es: {
      category: 'ROGUELITE · GODOT · PC Y ANDROID', headline: 'Un mundo nuevo,\npartida tras partida.',
      summary: 'Roguelite de acción top-down en desarrollo para PC y Android: héroes, armas, enemigos, capítulos, jefes y progresión. Nombre definitivo por definir.',
      context: 'Quería crear un juego de acción propio, con controles precisos, partidas rejugables y una identidad visual que funcione tanto en computadora como en celular.',
      system: 'El prototipo reúne selección de personaje, cuatro capítulos con cinco etapas, modos alternativos, cofres, perks, armas y mejoras permanentes. El proyecto continúa en desarrollo.',
      complexity: 'Combinar combate, enemigos, animación, controles táctiles y variedad de salas sin perder fluidez obliga a separar las mecánicas del contenido y a probar continuamente.',
      engineering: 'Godot 4.7 y GDScript; sistemas de personajes, armas y enemigos organizados por módulos, guardado versionado, pooling de proyectiles y herramientas de verificación automatizada.',
      impact: 'Es mi proyecto personal de videojuegos más activo: una plataforma para explorar diseño de combate, arte, experiencia de usuario y optimización en PC y Android.',
      decisions: [['Una base para seguir agregando contenido', 'Héroes, enemigos, armas y salas se describen de manera modular para poder ampliar el juego.'], ['Una identidad por capítulo', 'Las familias de enemigos y los escenarios cambian por capítulo para evitar mezclas arbitrarias.'], ['Diseñar para dos pantallas', 'Controles físicos y táctiles, lectura clara del combate y pruebas de rendimiento forman parte del desarrollo.']],
    },
    en: {
      category: 'ROGUELITE · GODOT · PC & ANDROID', headline: 'A new world,\none run at a time.',
      summary: 'A top-down action roguelite in development for PC and Android: heroes, weapons, enemies, chapters, bosses and progression. Final title to be decided.',
      context: 'I wanted to build my own action game with responsive controls, replayable runs and a visual identity that works on both desktop and mobile.',
      system: 'The prototype features character selection, four chapters with five stages, alternate modes, chests, perks, weapons and persistent upgrades. Development is ongoing.',
      complexity: 'Combining combat, enemies, animation, touch controls and room variety without sacrificing performance requires separating gameplay systems from content and testing often.',
      engineering: 'Godot 4.7 and GDScript, modular character, weapon and enemy systems, versioned saves, projectile pooling and automated verification tools.',
      impact: 'My most active personal game project, exploring combat design, visual direction, user experience and performance on PC and Android.',
      decisions: [['A foundation for more content', 'Heroes, enemies, weapons and rooms use modular definitions so the game can grow.'], ['Distinct chapter identities', 'Enemy families and environments change by chapter instead of mixing indiscriminately.'], ['Built for two kinds of screen', 'Physical and touch controls, clear combat feedback and performance checks shape development.']],
    },
  },
  {
    slug: 'servifood-tracking', number: '03', name: 'ServiFood Tracking · Panel de Mantenimiento', short: 'ServiFood Tracking', repo: 'app_mantenimiento_sf',
    stack: ['React', 'Vite', 'Supabase', 'PostgreSQL', 'SQL', 'Excel'],
    flow: { es: ['Trabajos', 'Personas y permisos', 'Datos', 'Vehículos y activos', 'Reportes'], en: ['Jobs', 'People and permissions', 'Data', 'Vehicles and assets', 'Reports'] },
    es: {
      category: 'MANTENIMIENTO · VEHÍCULOS · TRABAJOS', headline: 'El trabajo de campo,\nordenado en una app.',
      summary: 'Una plataforma para registrar trabajos, organizar personal, seguir vehículos, combustible, mantenimiento, costos, activos y vencimientos.',
      context: 'Los trabajos de mantenimiento ocurren en planta, en vehículos y con distintas personas. Hacía falta reunir esa información sin perder el contexto de cada tarea.',
      system: 'La app reúne trabajos diarios, solicitudes, trabajadores, grupos, costos y reportes. También incorpora vehículos, choferes, combustible, kilometraje, recorridos, mantenimiento y activos de planta.',
      complexity: 'Hay que relacionar personas, equipos, recorridos y mantenimientos sin volver la interfaz difícil de usar para quienes cargan información todos los días.',
      engineering: 'Está desarrollada con React y Vite sobre Supabase y PostgreSQL. Incluye roles, permisos, paneles, exportación a Excel y ayudas dentro de la propia aplicación.',
      impact: 'Permite registrar tareas, seguir solicitudes y consultar el historial de vehículos y activos desde un mismo lugar.',
      decisions: [['Representar el trabajo real', 'Trabajos, activos y vehículos conservan relaciones y contexto en lugar de quedar como registros aislados.'], ['Guardar el historial', 'Recorridos, mantenimientos y vencimientos son útiles porque se pueden seguir en el tiempo.'], ['Pensar en el uso diario', 'Paneles, filtros, reportes y ayuda integrada reducen fricción en tareas repetidas.']],
    },
    en: {
      category: 'MAINTENANCE · VEHICLES · JOBS', headline: 'Field work,\norganized in one app.',
      summary: 'A platform for jobs, staff, vehicles, fuel, maintenance, costs, assets and document deadlines.',
      context: 'Maintenance happens across facilities, vehicles and different teams. The information needed one shared place without losing the context of each job.',
      system: 'The app brings together daily jobs, requests, workers, groups, costs and reports, plus vehicles, drivers, fuel, mileage, routes, maintenance and plant assets.',
      complexity: 'People, equipment, journeys and maintenance events need to stay connected without making everyday data entry difficult.',
      engineering: 'It is built with React and Vite on Supabase and PostgreSQL, with roles, permissions, dashboards, Excel exports and in-app guidance.',
      impact: 'It lets teams record work, follow requests and review vehicle and asset history in one place.',
      decisions: [['Represent real work', 'Jobs, assets and vehicles keep their relationships and context instead of becoming isolated records.'], ['Keep the history', 'Routes, maintenance and deadlines become more useful when they can be followed over time.'], ['Design for daily use', 'Dashboards, filters, reports and built-in guidance reduce friction in repeated tasks.']],
    },
  },
  {
    slug: 'servifood-analytics', number: '04', name: 'ServiFood Analytics', short: 'Analytics', repo: 'analisis_app_servifood',
    stack: ['React 18', 'Vite', 'Material UI', 'Node.js 24', 'Express', 'Supabase', 'PostgreSQL', 'ExcelJS'],
    flow: { es: ['Excel', 'Validación', 'Base de datos', 'Paneles', 'Análisis'], en: ['Excel', 'Validation', 'Database', 'Dashboards', 'Analysis'] },
    es: {
      category: 'ANÁLISIS · EXCEL · CALIDAD', headline: 'De muchos archivos\na información útil.',
      summary: 'Plataforma de análisis y calidad: Excel, historial, documentos SGC, certificaciones e inspecciones BPM con seguimiento y controles de acceso.',
      context: 'Los archivos de trabajo tenían información útil, pero estaba repartida y era difícil mantener un historial consistente para comparar resultados.',
      system: 'Permite analizar Excel y desvíos anuales, administrar documentación SGC y certificaciones, gestionar usuarios y trabajar con inspecciones BPM y sus registros.',
      complexity: 'Los archivos deben validarse antes de usar sus datos y cada tipo de usuario necesita acceso distinto. El procesamiento también debe estar separado de la interfaz.',
      engineering: 'El frontend usa React, Vite y Material UI. El backend usa Node.js y Express. Supabase gestiona autenticación y PostgreSQL guarda la información; ExcelJS se ocupa de leer los archivos.',
      impact: 'Convierte archivos dispersos en información que se puede consultar, comparar y volver a utilizar desde una plataforma común.',
      decisions: [['Validar antes de guardar', 'Los archivos se revisan antes de convertir su contenido en información de trabajo.'], ['Separar interfaz y procesamiento', 'Express concentra el trabajo de servidor y React se enfoca en la experiencia y la visualización.'], ['Conservar el historial', 'Cada análisis puede consultarse después y formar parte de comparaciones posteriores.']],
    },
    en: {
      category: 'ANALYSIS · EXCEL · QUALITY', headline: 'From many files\nto useful information.',
      summary: 'An internal analytics and quality platform for Excel, history, SGC documents, certifications and BPM inspections with access controls.',
      context: 'Working files contained useful information, but it was scattered and difficult to keep as a consistent history for comparison.',
      system: 'The app handles Excel and annual deviation analysis, history, SGC documents, certifications, user administration and BPM inspection records.',
      complexity: 'Files need validation before their data is used, and different users need different access. Processing also needs to stay separate from the interface.',
      engineering: 'The frontend uses React, Vite and Material UI. The backend uses Node.js and Express. Supabase handles authentication, PostgreSQL stores the data and ExcelJS reads the files.',
      impact: 'It turns scattered files into information that can be reviewed, compared and reused from one shared platform.',
      decisions: [['Validate before storing', 'Files are checked before their contents become working data.'], ['Separate interface and processing', 'Express handles server work while React focuses on interaction and visualization.'], ['Keep the history', 'Each analysis remains available for later review and comparison.']],
    },
  },
  {
    slug: 'ep-consultora-sgi', number: '05', name: 'gestiQa · Gestión Integrada', short: 'gestiQa', repo: 'Aplicacion_de_SGI',
    stack: ['React 18', 'Vite', 'React Router', 'Supabase', 'PostgreSQL', 'RLS', 'Storage', 'Edge Functions', 'Vitest', 'GitHub Actions'],
    flow: { es: ['Empresa', 'Usuarios y permisos', 'Documentos privados', 'Revisión y aprobación', 'Historial'], en: ['Company', 'Users and permissions', 'Private documents', 'Review and approval', 'History'] },
    es: {
      category: 'DOCUMENTOS · EMPRESAS · APROBACIONES', headline: 'Cada documento,\ncon su recorrido.',
      summary: 'Una plataforma multiempresa para organizar documentos, responsables, versiones, revisiones, aprobaciones, vencimientos y requisitos ISO.',
      context: 'Guardar archivos no alcanza cuando hay responsables, versiones, revisiones y aprobaciones. Además, cada empresa debe trabajar solo con su propia documentación.',
      system: 'gestiQa centraliza documentación, usuarios, alertas y requisitos de ISO 9001, ISO 14001 e ISO 45001. Cada documento puede pasar por revisión, observaciones y aprobación, dejando historial.',
      complexity: 'Las empresas deben estar separadas entre sí y los documentos necesitan permisos, versiones y estados claros durante todo su recorrido.',
      engineering: 'React y Supabase forman la base. Auth y RLS controlan accesos; los archivos viven en Storage privado y se abren mediante enlaces firmados. El flujo de revisión y aprobación queda registrado.',
      impact: 'Permite a cada empresa organizar su documentación y seguir qué pasó con cada archivo, quién intervino y en qué estado se encuentra.',
      decisions: [['Cada empresa tiene su propio espacio', 'Los permisos evitan que una organización pueda consultar documentos de otra.'], ['Un documento tiene historia', 'Versiones, comentarios, revisores y aprobadores forman parte del mismo recorrido.'], ['Los archivos son privados', 'El acceso se entrega solo cuando corresponde y no mediante enlaces públicos permanentes.']],
    },
    en: {
      category: 'DOCUMENTS · COMPANIES · APPROVALS', headline: 'Every document\nhas a clear path.',
      summary: 'A multi-company platform for documents, owners, versions, reviews, approvals, deadlines and ISO requirements.',
      context: 'File storage is not enough when documents need owners, versions, reviews and approvals. Each company also needs to work only with its own information.',
      system: 'gestiQa brings together documents, users, alerts and ISO 9001, ISO 14001 and ISO 45001 requirements. Documents can move through review, comments and approval while keeping history.',
      complexity: 'Companies need to stay isolated from each other while documents keep clear permissions, versions and states throughout their lifecycle.',
      engineering: 'React and Supabase form the base. Auth and RLS control access; files live in private Storage and open through signed links. Review and approval steps are recorded.',
      impact: 'Each company can organize its documentation and see what happened to every file, who took part and what state it is in.',
      decisions: [['Each company has its own space', 'Permissions prevent one organization from viewing another company’s documents.'], ['A document keeps its history', 'Versions, comments, reviewers and approvers belong to the same record.'], ['Files stay private', 'Access is granted when needed instead of exposing permanent public links.']],
    },
  },
];
export const projectCopy = (project: Project, lang: Language) => project[lang];
