import type { Language } from '@/lib/site';
export const content = {
 es: {
  nav: ['Proyectos', 'Experiencia', 'Stack', 'Sobre mí', 'Contacto'], skip: 'Saltar al contenido', menu: 'Abrir navegación', close: 'Cerrar navegación',
  eyebrow: 'AGUSTÍN FERNANDO WOJTYSZYN', hero: ['Construyo sistemas', 'para el', 'mundo real.'],
  intro: 'Diseño y desarrollo aplicaciones completas que resuelven problemas reales y siguen mejorando después de publicarse.',
  role: 'Full Stack Web Developer', location: '26 años · San Juan, Argentina', work: 'Explorar proyectos',
  mapTitle: 'MAPA DE PROYECTOS', mapHint: 'Ver proyecto', mapCaption: 'Proyectos distintos. Una misma forma de construir.',
  selected: 'Proyectos destacados', selectedSub: 'No hago solo pantallas.\nConstruyo herramientas completas.', case: 'Ver proyecto',
  visual: 'ILUSTRACIÓN DEL PROYECTO · SIN DATOS REALES',
  ecosystemLabel: 'SERVIFOOD · PRODUCTOS QUE CRECIERON CON LA OPERACIÓN', ecosystemTitle: 'Una empresa.\nVarios sistemas.', ecosystemText: 'En ServiFood fui construyendo herramientas para pedidos, análisis y mantenimiento. Cada una nació de una necesidad distinta y siguió creciendo con el uso diario.',
  ecosystemFoot: 'Construir, publicar, mantener y seguir mejorando.',
  midnightLabel: 'PROYECTO PERSONAL', midnightText: 'MIDNIGHT PASS es mi juego de conducción para navegador: rutas conectadas, física en tiempo real y un mundo que sigo expandiendo.', roadNote: 'Representación visual del proyecto · no es una captura del juego', roadPause: 'Pausar escena', roadPlay: 'Animar escena',
  experienceLabel: 'EXPERIENCIA', experienceTitle: 'Publicar una app\nes solo el comienzo.', experienceIntro: 'Después vienen los usuarios reales, los cambios, los errores y las nuevas necesidades. Ahí también está el trabajo.',
  present: 'AGO 2024 — ACTUALIDAD', job: 'Full Stack Web Developer', jobText: 'Desarrollo y mantengo aplicaciones internas en ServiFood. Trabajo desde la idea y los datos hasta la interfaz, el deploy y la resolución de problemas cuando el sistema ya está en uso.',
  responsibilities: ['Entender el problema', 'Diseñar una solución', 'Construir y publicar', 'Mantener y mejorar'],
  education: 'Formación', schoolDate: 'AGO 2024 — DIC 2025', schoolText: 'Conquer Blocks · Full Stack Web Developer. Formación finalizada con presentación y defensa técnica de una aplicación.', english: 'Inglés · B2',
  stackLabel: 'TECNOLOGÍAS', stackTitle: 'Las herramientas\ncon las que trabajo.', stackText: 'No las muestro como porcentajes: las uso para resolver partes concretas de cada proyecto.',
  archiveLabel: 'RECORRIDO', archiveTitle: 'Cada proyecto\nme llevó al siguiente.', archiveText: 'Una selección de trabajos propios, desde las primeras interfaces hasta aplicaciones completas y proyectos 3D.',
  aboutLabel: 'SOBRE MÍ', aboutTitle: 'Me interesa lo que\npasa después del clic.', aboutText: 'Me gusta entender cómo funciona un proceso, detectar qué se puede mejorar y convertirlo en una herramienta clara. Por eso disfruto tanto el frontend como la lógica, los datos y la parte de mantener una aplicación cuando ya está en uso.',
  aboutSecond: 'Vivo en San Juan, Argentina. También me interesan mucho los autos y los juegos de conducción; de ahí nació MIDNIGHT PASS, mi proyecto personal más ambicioso. Uso IA como herramienta para acelerar trabajo, siempre revisando y tomando las decisiones técnicas.',
  contactLabel: 'CONTACTO', contactTitle: '¿Tenés una idea\no un problema por resolver?', contactCta: 'Hablemos.', contactText: 'Aplicaciones web, herramientas internas, automatización y proyectos que necesiten pasar de idea a producto.', footer: 'Hecho en San Juan, Argentina.', back: 'Volver a proyectos', context: 'El problema', system: 'Lo que construí', complexity: 'El desafío', engineering: 'Cómo lo hice', impact: 'Qué resuelve', decisions: 'Decisiones importantes', architecture: 'Cómo está armado', next: 'Siguiente proyecto', repository: 'Ver código en GitHub', privateRepo: 'Código privado', status: 'AGUSTÍN / EN RESUMEN', statusValues: ['Aplicaciones en uso real', 'Juego de conducción propio', 'San Juan, Argentina'], statusLabels: ['Trabajo', 'Proyecto personal', 'Base'],
 },
 en: {
  nav: ['Work', 'Experience', 'Stack', 'About', 'Contact'], skip: 'Skip to content', menu: 'Open navigation', close: 'Close navigation',
  eyebrow: 'AGUSTÍN FERNANDO WOJTYSZYN', hero: ['I build systems', 'for the', 'real world.'],
  intro: 'I design and build complete applications that solve real problems and keep improving after launch.',
  role: 'Full Stack Web Developer', location: '26 years old · San Juan, Argentina', work: 'Explore projects',
  mapTitle: 'PROJECT MAP', mapHint: 'View project', mapCaption: 'Different projects. The same hands-on approach.',
  selected: 'Selected projects', selectedSub: 'I do more than screens.\nI build complete tools.', case: 'View project',
  visual: 'PROJECT ILLUSTRATION · NO REAL OPERATIONAL DATA',
  ecosystemLabel: 'SERVIFOOD · PRODUCTS THAT GREW WITH DAILY WORK', ecosystemTitle: 'One company.\nSeveral systems.', ecosystemText: 'At ServiFood I built tools for orders, analysis and maintenance. Each one started with a different need and kept growing through daily use.',
  ecosystemFoot: 'Build, launch, maintain and improve.',
  midnightLabel: 'PERSONAL PROJECT', midnightText: 'MIDNIGHT PASS is my browser driving game: connected roads, real-time physics and a world I keep expanding.', roadNote: 'Visual interpretation of the project · not a game screenshot', roadPause: 'Pause scene', roadPlay: 'Animate scene',
  experienceLabel: 'EXPERIENCE', experienceTitle: 'Launching an app\nis only the beginning.', experienceIntro: 'Then come real users, changes, bugs and new needs. That is part of the job too.',
  present: 'AUG 2024 — PRESENT', job: 'Full Stack Web Developer', jobText: 'I build and maintain internal applications at ServiFood. I work from the initial idea and data model through the interface, deployment and problem solving once the software is in use.',
  responsibilities: ['Understand the problem', 'Design a solution', 'Build and launch', 'Maintain and improve'],
  education: 'Education', schoolDate: 'AUG 2024 — DEC 2025', schoolText: 'Conquer Blocks · Full Stack Web Developer. Completed with a technical presentation and defense of a developed application.', english: 'English · B2',
  stackLabel: 'TECHNOLOGIES', stackTitle: 'The tools\nI work with.', stackText: 'I use each tool for a concrete part of a project instead of showing meaningless skill percentages.',
  archiveLabel: 'JOURNEY', archiveTitle: 'Each project\nled to the next.', archiveText: 'A selection of original work, from early interfaces to complete applications and 3D projects.',
  aboutLabel: 'ABOUT ME', aboutTitle: 'I care about what\nhappens after the click.', aboutText: 'I like understanding how a process works, finding what can be improved and turning it into a clear tool. That is why I enjoy the interface, the logic, the data and the work of maintaining an application once people rely on it.',
  aboutSecond: 'I live in San Juan, Argentina. I am also very interested in cars and driving games; that led to MIDNIGHT PASS, my most ambitious personal project. I use AI to speed up work while keeping technical decisions and review in my hands.',
  contactLabel: 'CONTACT', contactTitle: 'Have an idea\nor a problem to solve?', contactCta: 'Let’s talk.', contactText: 'Web applications, internal tools, automation and projects that need to move from idea to product.', footer: 'Built in San Juan, Argentina.', back: 'Back to projects', context: 'The problem', system: 'What I built', complexity: 'The challenge', engineering: 'How I built it', impact: 'What it solves', decisions: 'Important decisions', architecture: 'How it works', next: 'Next project', repository: 'View code on GitHub', privateRepo: 'Private code', status: 'AGUSTÍN / IN SHORT', statusValues: ['Applications used in real work', 'Personal driving game', 'San Juan, Argentina'], statusLabels: ['Work', 'Personal project', 'Base'],
 }
};
export const getContent = (lang: Language) => content[lang];
export const stack = [
 { title: { es: 'Interfaz', en: 'Frontend' }, tools: 'React · Next.js · TypeScript', es: 'Pantallas, navegación y experiencias adaptadas a cada dispositivo.', en: 'Interfaces, navigation and responsive experiences.' },
 { title: { es: 'Backend', en: 'Backend' }, tools: 'Node.js · Express · REST', es: 'Reglas de negocio, APIs y validaciones.', en: 'Business rules, APIs and validation.' },
 { title: { es: 'Datos', en: 'Data' }, tools: 'PostgreSQL · SQL · Supabase', es: 'Información ordenada para representar procesos reales.', en: 'Structured information for real processes.' },
 { title: { es: 'Seguridad', en: 'Security' }, tools: 'Auth · RLS · Roles · Storage', es: 'Usuarios, permisos y acceso controlado a información.', en: 'Users, permissions and controlled access to information.' },
 { title: { es: 'Automatización', en: 'Automation' }, tools: 'RPC · Edge Functions · ExcelJS · jsPDF', es: 'Tareas automáticas, archivos, reportes y documentos.', en: 'Automated tasks, files, reports and documents.' },
 { title: { es: 'Pruebas', en: 'Testing' }, tools: 'Vitest · Testing Library · GitHub Actions', es: 'Pruebas para detectar errores antes de publicar cambios.', en: 'Checks that catch problems before changes are shipped.' },
 { title: { es: 'Producción', en: 'Production' }, tools: 'Render · Supabase · Git', es: 'Publicación, monitoreo, diagnóstico y mantenimiento.', en: 'Deployment, monitoring, diagnosis and maintenance.' },
 { title: { es: '3D / videojuegos', en: '3D / games' }, tools: 'Three.js · R3F · Rapier · LOD', es: 'Física, escenarios y rendimiento en tiempo real.', en: 'Physics, environments and real-time performance.' },
];
export const archive = [
 { era: '01', es: 'Primeras interfaces', en: 'Early interfaces', tech: 'HTML / CSS', projects: [{ name: 'Modern Art Gallery', repo: 'Modern-art-gallery' }, { name: 'LuxurySpa', repo: 'LuxurySpa' }] },
 { era: '02', es: 'Interacción y APIs', en: 'Interaction and APIs', tech: 'JAVASCRIPT / APIs', projects: [{ name: 'AppClima', repo: 'AppClima' }, { name: 'Javascriptex', repo: 'Javascriptex' }] },
 { era: '03', es: 'Aplicaciones completas', en: 'Complete applications', tech: 'REACT / FULL STACK', projects: [{ name: 'Skillconnect', repo: 'Skillconnect' }, { name: 'Divide tus gastos', repo: 'Divide-tus-gastos' }, { name: 'ArcadeReactApp', repo: 'ArcadeReactApp' }] },
 { era: '04', es: 'Trabajo real y proyectos propios', en: 'Real work and personal projects', tech: 'SISTEMAS / 3D', projects: [{ name: 'App de Pedidos · ServiFood', href: '#work' }, { name: 'MIDNIGHT PASS', href: '#midnight' }] },
];