import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { projects } from '@/content/projects';
import { getContent } from '@/content/site';
import { isLanguage,identity,siteUrl } from '@/lib/site';
import { Architecture,OrderVisual } from '@/components/architecture';
import { Road } from '@/components/road';
import { Contact,Footer } from '@/sections/home';
type Params={params:Promise<{lang:string;slug:string}>};
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:Params):Promise<Metadata>{const {lang,slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p||!isLanguage(lang))notFound();return {title:p.name,description:p[lang].summary,alternates:{canonical:`/${lang}/work/${slug}`,languages:{es:`/es/work/${slug}`,en:`/en/work/${slug}`}},openGraph:{title:`${p.name} — Agustín Wojtyszyn`,description:p[lang].summary,url:`/${lang}/work/${slug}`,images:[{url:'/opengraph-image',width:1200,height:630}]},twitter:{card:'summary_large_image',title:p.name,description:p[lang].summary,images:['/opengraph-image']}};}
export default async function CaseStudy({params}:Params){
 const {lang,slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p||!isLanguage(lang))notFound();const c=p[lang],t=getContent(lang),next=projects[(projects.indexOf(p)+1)%projects.length];
 const schema={'@context':'https://schema.org','@type':'CreativeWork',name:p.name,description:c.summary,author:{'@type':'Person',name:identity.name},url:`${siteUrl}/${lang}/work/${slug}`,inLanguage:lang};
 return <><main id="main" className="case-main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><section className="container case-hero"><Link className="text-link back-link" href={`/${lang}#work`}>← {t.back}</Link><div className="case-kicker eyebrow"><span>{p.number} / {lang==='es'?'PROYECTO':'PROJECT'}</span><span>{c.category}</span></div><h1>{c.headline}</h1><div className="case-intro"><h2>{p.name}</h2><p>{c.summary}</p></div><div className="case-meta"><span className="mono">{p.slug==='midnight-pass'?(lang==='es'?'PROYECTO 3D INTERACTIVO':'INTERACTIVE 3D PROJECT'):(lang==='es'?'DESARROLLO FULL STACK':'FULL STACK DEVELOPMENT')}</span>{p.repo?<a className="text-link" href={`${identity.github}/${p.repo}`} target="_blank" rel="noreferrer">{t.repository} ↗</a>:<span className="mono muted">{t.privateRepo}</span>}</div></section><section className="container case-visual" aria-label={t.architecture}>{p.slug==='midnight-pass'?<Road lang={lang}/>:p.slug==='servifood-orders'?<OrderVisual lang={lang}/>:<Architecture flow={p.flow[lang]} lang={lang}/>}</section><section className="container section case-narrative"><aside><p className="eyebrow">{p.name}</p><nav aria-label={lang==='es'?'Secciones del proyecto':'Project sections'}>{(['context','system','complexity','engineering','impact'] as const).map(k=><a key={k} href={`#${k}`}>{t[k]} ↗</a>)}</nav></aside><div>{(['context','system','complexity','engineering','impact'] as const).map((k,i)=><article key={k} id={k}><p className="eyebrow">0{i+1} / {t[k]}</p><h2>{k==='context'?(lang==='es'?'El punto de partida.':'The starting point.'):k==='system'?(lang==='es'?'Lo que construí.':'What I built.'):k==='complexity'?(lang==='es'?'El desafío.':'The challenge.'):k==='engineering'?(lang==='es'?'Cómo lo resolví.':'How I built it.'):t.impact}</h2><p>{c[k]}</p></article>)}</div></section><section className="section decisions-section"><div className="container"><p className="eyebrow">{lang==='es'?'DECISIONES DEL PROYECTO':'PROJECT DECISIONS'}</p><h2>{t.decisions}</h2><div className="decisions-grid">{c.decisions.map(([title,body],i)=><article key={title}><span className="mono">0{i+1} ↘</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section><section className="container section case-stack"><div><p className="eyebrow">{lang==='es'?'TECNOLOGÍAS':'STACK'} / {p.short}</p><h2>{t.architecture}</h2><p className="case-tech mono">{p.stack.join(' · ')}</p></div><Architecture flow={p.flow[lang]} lang={lang}/></section><Link className="container next-case" href={`/${lang}/work/${next.slug}`}><span className="eyebrow">{t.next} / {next.number}</span><strong>{next.name}</strong><span>↗</span></Link><Contact lang={lang}/></main><Footer lang={lang}/></>;
}